version: "3.8"

services:
#  cassandra:
#    image: library/cassandra:latest
#    container_name: cassandra
#    ports:
#    - "7000:7000"
#    - "9042:9042"
#    environment:
#      - "CASSANDRA_CLUSTER_NAME=OUR_DOCKERIZED_CASSANDRA_SINGLE_NODE_CLUSTER"
  nkm-actor-server:
    restart: always
    image: tojatos/scala-sbt:8u222_1.3.5_2.13.1
    command: sh -c "sbt run"
    working_dir: /NKMActorServer
    volumes:
      - ./:/NKMActorServer
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nkm-actor-server.rule=((Host(`krzysztofruczkowski.pl`) || Host(`www.krzysztofruczkowski.pl`)) && PathPrefix(`/nkm/`))"
      - "traefik.http.routers.nkm-actor-server.priority=1"
      - "traefik.http.routers.nkm-actor-server.tls=true"
      - "traefik.http.routers.nkm-actor-server.tls.certresolver=myresolver"
      - "traefik.http.services.nkm-actor-server.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_default"

networks:
  web:
    name: traefik_default
    external: true
