version: "3.8"

services:
  nkm-actor-server:
    restart: always
    build: .
    image: tojatos/nkm-actor-server:stable
    networks:
      - web
      - default
    environment:
      - PORT=80
      - MYSQL_HOST=db
      - MYSQL_DB=nkm_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=nkm_db_pass
      - MYSQL_PORT=3306
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nkm-actor-server-stripprefix.stripPrefix.prefixes=/nkm"
      - "traefik.http.routers.nkm-actor-server.rule=((Host(`krzysztofruczkowski.pl`) || Host(`www.krzysztofruczkowski.pl`)) && PathPrefix(`/nkm/`))"
      - "traefik.http.routers.nkm-actor-server.middlewares=nkm-actor-server-stripprefix"
      - "traefik.http.routers.nkm-actor-server.tls=true"
      - "traefik.http.routers.nkm-actor-server.tls.certresolver=myresolver"
      - "traefik.http.services.nkm-actor-server.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_default"
    depends_on:
      - db
  db:
    restart: always
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nkm_db
      - MYSQL_ROOT_PASSWORD=nkm_db_pass
    expose:
      - 3306

networks:
  web:
    name: traefik_default
    external: true

volumes:
  mysql_data:
