version: "3.8"

services:
  nkm-actor-server-dev:
    restart: always
    build: .
    image: tojatos/nkm-actor-server-dev
    environment:
      - PORT=3737
      - MYSQL_HOST=db
      - MYSQL_DB=nkm_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    ports:
      - 3737:3737
    depends_on:
      - db
  db:
    restart: always
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nkm_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    expose:
      - 3306

volumes:
  mysql_data:
