version: "3.8"

services:
  cassandra:
    image: library/cassandra:latest
    container_name: cassandra
    ports:
    - "7000:7000"
    - "9042:9042"
    environment:
      - "CASSANDRA_CLUSTER_NAME=OUR_DOCKERIZED_CASSANDRA_SINGLE_NODE_CLUSTER"
